######################
#     Configured     #
######################
# Set this to true once you have configured the configuration.
configured: false

###############
#     Bot     #
###############
# Discord Bot Configuration.
bot:

  # The token of the bot that should be used.
  token: "INSERT_TOKEN_HERE"

  # Possible options: Online, Idle, Do Not Disturb, Offline.
  online_status: "Online"

  # Possible options: Watching, Listening, Do Not Disturb, playing.
  activity: "playing"

  # Change the status to anything you want! For Example "play.hypixel.net"!
  status: ""

###################
#     Database    #
###################
# Used to keep track of player linking.
database:

  # The host of the database. 'localhost' and '127.0.0.1' both point to the local machine
  host: ""

  # The port to use.
  port: ""

  # The database to use.
  database: ""

  # The username to use to login to the database.
  username: ""

  # The password to use to login to the database.
  password: ""