######################
#     Configured     #
######################
# Set this to true once you have configured the configuration.
configured: false

###############
#     Bot     #
###############
# Discord Bot Configuration.
bot:

  # Whether or not the usage of a bot is enabled.
  enabled: false

  # The token of the bot that should be used.
  token: "INSERT_TOKEN_HERE"

  # Possible options: Online, Idle, Do Not Disturb, Offline.
  online_status: "Online"

  # Possible options: Watching, Listening, Do Not Disturb, playing.
  activity: "playing"

  # Change the status to anything you want! For Example "play.hypixel.net"!
  status: ""

###################
#     Database    #
###################
# Used to keep track of player linking.
database:

  # Possible options: SQLite, MySQL, MariaDB
  type: "SQLite"

  # The host of the database. 'localhost' and '127.0.0.1' both point to the local machine
  host: "127.0.0.1"

  # The database to use. Make sure it is created before attempting to connect.
  # Points to a file path from the plugin directory for SQLite. Do not include .db
  database: ""

  # The username to use to login to the database. Leave blank for SQLite
  username: ""

  # The password to use to login to the database. Leave blank for SQLite
  password: ""

  # The prefix to prepend to all created tables
  table_prefix: "tdl_"